name: Prettier

on:
  pull_request:
    branches:
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Prettier
        run: npm install

      - name: Run Prettier
        run: npx prettier --check .